# Complexity thresholds
cognitive-complexity-threshold = 20
too-many-arguments-threshold = 6
type-complexity-threshold = 250

# Performance
perf-allocation-size-threshold = 2000
perf-unnecessary-operation-threshold = 100

# Documentation
doc-valid-idents = ["RFC", "API", "TCP", "UDP", "HTTP", "HTTPS", "IO"]

# Type safety
arithmetic-side-effects-allowed = false
float-arithmetic-allowed = true

# Style preferences
blacklisted-names = ["foo", "bar", "baz"]
