# Complexity thresholds
cognitive-complexity-threshold = 20
too-many-arguments-threshold = 6
type-complexity-threshold = 250

# Documentation
doc-valid-idents = ["RFC", "API", "TCP", "UDP", "HTTP", "HTTPS", "IO"]

# Type safety
arithmetic-side-effects-allowed-binary = false
arithmetic-side-effects-allowed-unary = false

# Style preferences
disallowed-names = ["foo", "bar", "baz"]
