# Formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

# Imports and modules
reorder_imports = true
reorder_modules = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"

# Code structure
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
format_assert_args = true

# Comments and documentation
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true

# Modern Rust features
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2024"

# Consistency
merge_derives = true
remove_nested_parens = true
match_block_trailing_comma = true
trailing_semicolon = true
