name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "src-tauri/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "src-tauri/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/backend-ci.yml"

jobs:
  test:
    name: Test Rust Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf libsoup2.4-dev

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --all-features

      - name: Check build
        run: cargo check --all-features

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit
